// GENERATED by tool/gen_protocol.dart — do not edit.
// Source: protocol/hp6_formats.json (healthypi 0.1.0),
// the host mirror of app_m7/src/core/sample_formats.h.

/// `.HP6` format version these layouts describe.
const int hp6FormatVersion = 0x0300;

/// DBLK frame: header, payload, trailing CRC-32.
const int dblkHeaderLen = 28;
const int dblkCrcLen = 4;
const int dblkOverhead = dblkHeaderLen + dblkCrcLen;

/// DBLK channel ids (header byte 20).
abstract final class Hp6Channel {
  static const int ecg = 1;
  static const int ppg = 2;
  static const int resp = 3;
  static const int vitals = 4;
  static const int eeg = 5;
  static const int event = 6;
  static const int sync = 7;
  static const int infer = 8;
}

/// Bytes per sample struct, by channel. A block whose payload does not
/// divide into these is a layout mismatch and is rejected.
const Map<int, int> hp6SampleSize = {
  Hp6Channel.ecg: 20, // <4iBBH
  Hp6Channel.ppg: 12, // <2iB3x
  Hp6Channel.vitals: 16, // <HHHhHHHBx
  Hp6Channel.eeg: 36, // <8iB3x
  Hp6Channel.event: 8, // <IHH
  Hp6Channel.sync: 40, // <IIQIIIIII
  Hp6Channel.infer: 16, // <IHBB5bB2x
};

/// `hp6_ecg_sample.lead_off`: electrode bits, set = off.
abstract final class Hp6LeadOff {
  static const int ra = 0x01;
  static const int la = 0x02;
  static const int ll = 0x04;
  static const int v1 = 0x08;
}

/// `hp6_vitals.flags`: HR provenance and quality.
abstract final class Hp6VitalsFlag {
  static const int hrFromPpg = 0x01;
  static const int ecgLeadOff = 0x02;
  static const int ppgWeak = 0x04;
  static const int motion = 0x08;
}

/// `hp6_infer_sample.flags`.
abstract final class Hp6InferFlag {
  static const int stub = 0x01;
  static const int lowConf = 0x02;
  static const int ecgSuspect = 0x04;
}
