// GENERATED by tool/gen_protocol.dart — do not edit.
// Source: protocol/hpi_group64.json (healthypi 0.1.0, schema 0x0002).
// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars

import 'dart:typed_data';

import 'hpi_command.dart';

/// Group-64 schema version this file was generated from.
const int hpiSchemaVersion = 2;

/// Every group-64 command id the firmware declares.
abstract final class Hpi {
  static const deviceInfo = HpiCommand(0x0001, 'device_info', read: true);
  /// ENOTSUP when no unlock secret is provisioned
  static const unlockChallenge = HpiCommand(0x0010, 'unlock_challenge', read: true);
  static const unlockResponse = HpiCommand(0x0011, 'unlock_response', write: true, errors: [264, 265, 266]);
  static const lock = HpiCommand(0x0012, 'lock', write: true);
  static const lockState = HpiCommand(0x0013, 'lock_state', read: true);
  /// empty response on success; data lands on CDC0
  static const streamStart = HpiCommand(0x0020, 'stream_start', write: true, unlock: true, errors: [258]);
  /// idempotent
  static const streamStop = HpiCommand(0x0021, 'stream_stop', write: true);
  static const streamStatus = HpiCommand(0x0022, 'stream_status', read: true);
  static const telemetry = HpiCommand(0x0030, 'telemetry', read: true);
  static const fwVersions = HpiCommand(0x0031, 'fw_versions', read: true);
  /// keyed by slot, NOT an array
  static const moduleList = HpiCommand(0x0050, 'module_list', read: true);
  static const moduleInfo = HpiCommand(0x0051, 'module_info', status: HpiStatus.unreachable);
  static const modulePower = HpiCommand(0x0052, 'module_power', write: true, unlock: true);
  /// raw bytes; the device does not parse the image
  static const moduleEepromRead = HpiCommand(0x0053, 'module_eeprom_read', read: true, unlock: true, errors: [256, 257]);
  /// identity takes effect at the next detect (module_power on)
  static const moduleEepromWrite = HpiCommand(0x0054, 'module_eeprom_write', write: true, unlock: true, errors: [256, 257]);
  /// bring-up: both slots share one bus, so this says whether it works
  static const moduleI2cScan = HpiCommand(0x0055, 'module_i2c_scan', read: true, unlock: true, errors: [256, 257]);
  static const sdStatus = HpiCommand(0x0060, 'sd_status', read: true);
  /// 256 covers BOTH already-recording and no-card; call sd_status to tell them apart
  static const sdRecordStart = HpiCommand(0x0061, 'sd_record_start', write: true, unlock: true, errors: [256]);
  static const sdRecordStop = HpiCommand(0x0062, 'sd_record_stop', write: true);
  static const sdList = HpiCommand(0x0063, 'sd_list', status: HpiStatus.unreachable);
  static const sdDownloadBegin = HpiCommand(0x0064, 'sd_download_begin', status: HpiStatus.unreachable);
  static const sdDownloadChunk = HpiCommand(0x0065, 'sd_download_chunk', status: HpiStatus.unreachable);
  static const sdDownloadEnd = HpiCommand(0x0066, 'sd_download_end', status: HpiStatus.unreachable);
  static const sdDelete = HpiCommand(0x0067, 'sd_delete', status: HpiStatus.unreachable);
  static const sdFormat = HpiCommand(0x0068, 'sd_format', status: HpiStatus.unreachable);
  /// arming re-enumerates USB and kills the open CDC1 connection
  static const transferMode = HpiCommand(0x0069, 'transfer_mode', read: true, write: true, unlock: true, errors: [267, 257]);
  static const wifiStatus = HpiCommand(0x0070, 'wifi_status', read: true, errors: [257]);
  /// always ENOTSUP: provisioning goes through the SoftAP portal
  static const wifiScan = HpiCommand(0x0071, 'wifi_scan', read: true, status: HpiStatus.stub);
  static const wifiSet = HpiCommand(0x0072, 'wifi_set', write: true, unlock: true);
  static const wifiForget = HpiCommand(0x0073, 'wifi_forget', write: true, unlock: true);
  /// deliberately NOT unlock-gated: it is how a locked device gets online
  static const wifiSoftap = HpiCommand(0x0074, 'wifi_softap', write: true, errors: [257]);
  /// radios bitmask: bit0 WiFi, bit1 BLE; 0 = powered with no radio (needed to flash the C6, which cannot enumerate while held in reset). Answers 'accepted', not 'radio up' -- poll conn_status for the outcome
  static const connEnable = HpiCommand(0x0075, 'conn_enable', write: true, errors: [257]);
  /// radios down and the co-processor back into reset
  static const connDisable = HpiCommand(0x0076, 'conn_disable', write: true);
  /// link: 0 off (by request) 1 starting 2 up 3 fault -- the distinction wifi_status cannot express, between a radio that is off because it was asked to be and a co-processor that should be answering and is not
  static const connStatus = HpiCommand(0x0077, 'conn_status', read: true);
  /// `health` is a NESTED map; top-level `m4` (bool) differs from health.m4 (uint)
  static const diagRunSelftest = HpiCommand(0x0080, 'diag_run_selftest', read: true);
  /// a large age_ms means the ECG went quiet -- NOT the same as leads on
  static const diagLeadOff = HpiCommand(0x0081, 'diag_lead_off', read: true);
  static const diagSignalStats = HpiCommand(0x0082, 'diag_signal_stats', status: HpiStatus.unreachable);
  static const logSubscribe = HpiCommand(0x0090, 'log_subscribe', status: HpiStatus.unreachable);
  static const logUnsubscribe = HpiCommand(0x0091, 'log_unsubscribe', status: HpiStatus.unreachable);
  static const logGetBuffered = HpiCommand(0x0092, 'log_get_buffered', status: HpiStatus.unreachable);
  static const m4fwBegin = HpiCommand(0x00A0, 'm4fw_begin', write: true, unlock: true, signedBuild: true, errors: [256, 269, 270]);
  static const m4fwChunk = HpiCommand(0x00A1, 'm4fw_chunk', write: true, unlock: true, signedBuild: true, errors: [256, 260]);
  static const m4fwCommit = HpiCommand(0x00A2, 'm4fw_commit', write: true, unlock: true, signedBuild: true, errors: [268, 269, 270, 271]);
  /// call FIRST: `sig` says whether an unsigned upload will be rejected
  static const m4fwStatus = HpiCommand(0x00A3, 'm4fw_status', read: true, signedBuild: true);
  static const m4fwAbort = HpiCommand(0x00A4, 'm4fw_abort', write: true, signedBuild: true);
  /// reboots into MCUboot serial recovery; group 64 disappears until reflash
  static const enterRecovery = HpiCommand(0x00A5, 'enter_recovery', read: true, write: true, errors: [256]);

  static const List<HpiCommand> all = [
    deviceInfo,
    unlockChallenge,
    unlockResponse,
    lock,
    lockState,
    streamStart,
    streamStop,
    streamStatus,
    telemetry,
    fwVersions,
    moduleList,
    moduleInfo,
    modulePower,
    moduleEepromRead,
    moduleEepromWrite,
    moduleI2cScan,
    sdStatus,
    sdRecordStart,
    sdRecordStop,
    sdList,
    sdDownloadBegin,
    sdDownloadChunk,
    sdDownloadEnd,
    sdDelete,
    sdFormat,
    transferMode,
    wifiStatus,
    wifiScan,
    wifiSet,
    wifiForget,
    wifiSoftap,
    connEnable,
    connDisable,
    connStatus,
    diagRunSelftest,
    diagLeadOff,
    diagSignalStats,
    logSubscribe,
    logUnsubscribe,
    logGetBuffered,
    m4fwBegin,
    m4fwChunk,
    m4fwCommit,
    m4fwStatus,
    m4fwAbort,
    enterRecovery,
  ];
}

/// Request map for `device_info` (0x0001), read op.
Map<String, Object?> deviceInfoRequest() => const {};

/// Reply to `device_info` (0x0001), read op.
class DeviceInfoReply {
  const DeviceInfoReply({this.sn, this.fw, this.gv, this.br, this.hw, this.m4fw, this.espfw, this.up});

  factory DeviceInfoReply.fromMap(Map<Object?, Object?> m) => DeviceInfoReply(
        sn: hpiStr(m['sn']),
        fw: hpiStr(m['fw']),
        gv: hpiInt(m['gv']),
        br: hpiStr(m['br']),
        hw: hpiBytes(m['hw']),
        m4fw: hpiStr(m['m4fw']),
        espfw: hpiStr(m['espfw']),
        up: hpiInt(m['up']),
      );

  /// `sn` — serial number
  final String? sn;

  /// `fw` — M7 firmware version
  final String? fw;

  /// `gv` — group schema version
  final int? gv;

  /// `br` — board revision
  final String? br;

  /// `hw` — hardware id blob
  final Uint8List? hw;

  /// `m4fw`
  final String? m4fw;

  /// `espfw`
  final String? espfw;

  /// `up` — uptime, seconds
  final int? up;
}

/// Request map for `unlock_challenge` (0x0010), read op.
Map<String, Object?> unlockChallengeRequest() => const {};

/// Reply to `unlock_challenge` (0x0010), read op.
class UnlockChallengeReply {
  const UnlockChallengeReply({this.nonce, this.ttlMs});

  factory UnlockChallengeReply.fromMap(Map<Object?, Object?> m) => UnlockChallengeReply(
        nonce: hpiBytes(m['nonce']),
        ttlMs: hpiInt(m['ttl_ms']),
      );

  /// `nonce`
  final Uint8List? nonce;

  /// `ttl_ms`
  final int? ttlMs;
}

/// Request map for `unlock_response` (0x0011), write op.
Map<String, Object?> unlockResponseRequest({required List<int> tag}) => {
      'tag': Uint8List.fromList(tag),
    };

/// Reply to `unlock_response` (0x0011), write op.
class UnlockResponseReply {
  const UnlockResponseReply({this.state, this.ttlMs});

  factory UnlockResponseReply.fromMap(Map<Object?, Object?> m) => UnlockResponseReply(
        state: hpiInt(m['state']),
        ttlMs: hpiInt(m['ttl_ms']),
      );

  /// `state`
  final int? state;

  /// `ttl_ms` — grant remaining
  final int? ttlMs;
}

/// Request map for `lock` (0x0012), write op.
Map<String, Object?> lockRequest() => const {};

/// Reply to `lock` (0x0012), write op.
class LockReply {
  const LockReply({this.state});

  factory LockReply.fromMap(Map<Object?, Object?> m) => LockReply(
        state: hpiInt(m['state']),
      );

  /// `state`
  final int? state;
}

/// Request map for `lock_state` (0x0013), read op.
Map<String, Object?> lockStateRequest() => const {};

/// Reply to `lock_state` (0x0013), read op.
class LockStateReply {
  const LockStateReply({this.state});

  factory LockStateReply.fromMap(Map<Object?, Object?> m) => LockStateReply(
        state: hpiInt(m['state']),
      );

  /// `state`
  final int? state;
}

/// Request map for `stream_start` (0x0020), write op.
Map<String, Object?> streamStartRequest({required int ch, required int ann}) => {
      'ch': ch,
      'ann': ann,
    };

/// Request map for `stream_stop` (0x0021), write op.
Map<String, Object?> streamStopRequest() => const {};

/// Request map for `stream_status` (0x0022), read op.
Map<String, Object?> streamStatusRequest() => const {};

/// Reply to `stream_status` (0x0022), read op.
class StreamStatusReply {
  const StreamStatusReply({this.active, this.ch, this.ann, this.sent, this.dropped});

  factory StreamStatusReply.fromMap(Map<Object?, Object?> m) => StreamStatusReply(
        active: hpiBool(m['active']),
        ch: hpiInt(m['ch']),
        ann: hpiInt(m['ann']),
        sent: hpiInt(m['sent']),
        dropped: hpiInt(m['dropped']),
      );

  /// `active`
  final bool? active;

  /// `ch`
  final int? ch;

  /// `ann`
  final int? ann;

  /// `sent`
  final int? sent;

  /// `dropped`
  final int? dropped;
}

/// Request map for `telemetry` (0x0030), read op.
Map<String, Object?> telemetryRequest() => const {};

/// Reply to `telemetry` (0x0030), read op.
class TelemetryReply {
  const TelemetryReply({this.vbatMv, this.ibatMa, this.soc, this.tcX10, this.charge, this.usb, this.batt, this.usbAtt, this.ok});

  factory TelemetryReply.fromMap(Map<Object?, Object?> m) => TelemetryReply(
        vbatMv: hpiInt(m['vbat_mv']),
        ibatMa: hpiInt(m['ibat_ma']),
        soc: hpiInt(m['soc']),
        tcX10: hpiInt(m['tc_x10']),
        charge: hpiInt(m['charge']),
        usb: hpiBool(m['usb']),
        batt: hpiBool(m['batt']),
        usbAtt: hpiBool(m['usb_att']),
        ok: hpiBool(m['ok']),
      );

  /// `vbat_mv`
  final int? vbatMv;

  /// `ibat_ma`
  final int? ibatMa;

  /// `soc` — state of charge, %
  final int? soc;

  /// `tc_x10` — always the unavailable sentinel in 1.0.0
  final int? tcX10;

  /// `charge`
  final int? charge;

  /// `usb` — input supply present (charger PGOOD)
  final bool? usb;

  /// `batt` — literally !usb
  final bool? batt;

  /// `usb_att` (optional) — a USB host is enumerated -- NOT the same as usb
  final bool? usbAtt;

  /// `ok`
  final bool? ok;
}

/// Request map for `fw_versions` (0x0031), read op.
Map<String, Object?> fwVersionsRequest() => const {};

/// Reply to `fw_versions` (0x0031), read op.
class FwVersionsReply {
  const FwVersionsReply({this.m7fw, this.m4fw, this.espfw, this.modAFw, this.modBFw});

  factory FwVersionsReply.fromMap(Map<Object?, Object?> m) => FwVersionsReply(
        m7fw: hpiStr(m['m7fw']),
        m4fw: hpiStr(m['m4fw']),
        espfw: hpiStr(m['espfw']),
        modAFw: hpiStr(m['mod_a_fw']),
        modBFw: hpiStr(m['mod_b_fw']),
      );

  /// `m7fw`
  final String? m7fw;

  /// `m4fw`
  final String? m4fw;

  /// `espfw`
  final String? espfw;

  /// `mod_a_fw`
  final String? modAFw;

  /// `mod_b_fw`
  final String? modBFw;
}

/// Request map for `module_list` (0x0050), read op.
Map<String, Object?> moduleListRequest() => const {};

/// Reply to `module_list` (0x0050), read op.
class ModuleListReply {
  const ModuleListReply({this.a, this.b});

  factory ModuleListReply.fromMap(Map<Object?, Object?> m) => ModuleListReply(
        a: ModuleListReplyA.fromValue(m['a']),
        b: ModuleListReplyB.fromValue(m['b']),
      );

  /// `a` — slot A
  final ModuleListReplyA? a;

  /// `b` — slot B
  final ModuleListReplyB? b;
}

/// The `a` map of [ModuleListReply].
class ModuleListReplyA {
  const ModuleListReplyA({this.state, this.id, this.pwr, this.name});

  factory ModuleListReplyA.fromMap(Map<Object?, Object?> m) => ModuleListReplyA(
        state: hpiInt(m['state']),
        id: hpiInt(m['id']),
        pwr: hpiBool(m['pwr']),
        name: hpiStr(m['name']),
      );

  static ModuleListReplyA? fromValue(Object? v) =>
      v is Map ? ModuleListReplyA.fromMap(v) : null;

  /// `state`
  final int? state;

  /// `id`
  final int? id;

  /// `pwr`
  final bool? pwr;

  /// `name`
  final String? name;
}

/// The `b` map of [ModuleListReply].
class ModuleListReplyB {
  const ModuleListReplyB({this.state, this.id, this.pwr, this.name});

  factory ModuleListReplyB.fromMap(Map<Object?, Object?> m) => ModuleListReplyB(
        state: hpiInt(m['state']),
        id: hpiInt(m['id']),
        pwr: hpiBool(m['pwr']),
        name: hpiStr(m['name']),
      );

  static ModuleListReplyB? fromValue(Object? v) =>
      v is Map ? ModuleListReplyB.fromMap(v) : null;

  /// `state`
  final int? state;

  /// `id`
  final int? id;

  /// `pwr`
  final bool? pwr;

  /// `name`
  final String? name;
}

/// Request map for `module_power` (0x0052), write op.
Map<String, Object?> modulePowerRequest({required int slot, required bool on}) => {
      'slot': slot,
      'on': on,
    };

/// Reply to `module_power` (0x0052), write op.
class ModulePowerReply {
  const ModulePowerReply({this.ok});

  factory ModulePowerReply.fromMap(Map<Object?, Object?> m) => ModulePowerReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `module_eeprom_read` (0x0053), read op.
Map<String, Object?> moduleEepromReadRequest({required int slot, required int off, required int len}) => {
      'slot': slot,
      'off': off,
      'len': len,
    };

/// Reply to `module_eeprom_read` (0x0053), read op.
class ModuleEepromReadReply {
  const ModuleEepromReadReply({this.off, this.data});

  factory ModuleEepromReadReply.fromMap(Map<Object?, Object?> m) => ModuleEepromReadReply(
        off: hpiInt(m['off']),
        data: hpiBytes(m['data']),
      );

  /// `off`
  final int? off;

  /// `data`
  final Uint8List? data;
}

/// Request map for `module_eeprom_write` (0x0054), write op.
Map<String, Object?> moduleEepromWriteRequest({required int slot, required int off, required List<int> data}) => {
      'slot': slot,
      'off': off,
      'data': Uint8List.fromList(data),
    };

/// Reply to `module_eeprom_write` (0x0054), write op.
class ModuleEepromWriteReply {
  const ModuleEepromWriteReply({this.off, this.len});

  factory ModuleEepromWriteReply.fromMap(Map<Object?, Object?> m) => ModuleEepromWriteReply(
        off: hpiInt(m['off']),
        len: hpiInt(m['len']),
      );

  /// `off`
  final int? off;

  /// `len`
  final int? len;
}

/// Request map for `module_i2c_scan` (0x0055), read op.
Map<String, Object?> moduleI2cScanRequest({required int slot, bool? pwr}) => {
      'slot': slot,
      'pwr': ?pwr,
    };

/// Reply to `module_i2c_scan` (0x0055), read op.
class ModuleI2cScanReply {
  const ModuleI2cScanReply({this.addrs});

  factory ModuleI2cScanReply.fromMap(Map<Object?, Object?> m) => ModuleI2cScanReply(
        addrs: hpiBytes(m['addrs']),
      );

  /// `addrs` — responding 7-bit addresses
  final Uint8List? addrs;
}

/// Request map for `sd_status` (0x0060), read op.
Map<String, Object?> sdStatusRequest() => const {};

/// Reply to `sd_status` (0x0060), read op.
class SdStatusReply {
  const SdStatusReply({this.active, this.bytes, this.dur, this.ecg, this.ppg, this.path});

  factory SdStatusReply.fromMap(Map<Object?, Object?> m) => SdStatusReply(
        active: hpiBool(m['active']),
        bytes: hpiInt(m['bytes']),
        dur: hpiInt(m['dur']),
        ecg: hpiInt(m['ecg']),
        ppg: hpiInt(m['ppg']),
        path: hpiStr(m['path']),
      );

  /// `active`
  final bool? active;

  /// `bytes`
  final int? bytes;

  /// `dur` — ms
  final int? dur;

  /// `ecg` — samples
  final int? ecg;

  /// `ppg` — samples
  final int? ppg;

  /// `path`
  final String? path;
}

/// Request map for `sd_record_start` (0x0061), write op.
Map<String, Object?> sdRecordStartRequest({String? name}) => {
      'name': ?name,
    };

/// Reply to `sd_record_start` (0x0061), write op.
class SdRecordStartReply {
  const SdRecordStartReply({this.path});

  factory SdRecordStartReply.fromMap(Map<Object?, Object?> m) => SdRecordStartReply(
        path: hpiStr(m['path']),
      );

  /// `path`
  final String? path;
}

/// Request map for `sd_record_stop` (0x0062), write op.
Map<String, Object?> sdRecordStopRequest() => const {};

/// Request map for `transfer_mode` (0x0069), read op.
Map<String, Object?> transferModeRequest() => const {};

/// Reply to `transfer_mode` (0x0069), read op.
class TransferModeReply {
  const TransferModeReply({this.armed});

  factory TransferModeReply.fromMap(Map<Object?, Object?> m) => TransferModeReply(
        armed: hpiBool(m['armed']),
      );

  /// `armed`
  final bool? armed;
}

/// Request map for `transfer_mode` (0x0069), write op.
Map<String, Object?> transferModeWriteRequest({required bool on}) => {
      'on': on,
    };

/// Reply to `transfer_mode` (0x0069), write op.
class TransferModeWriteReply {
  const TransferModeWriteReply({this.armed});

  factory TransferModeWriteReply.fromMap(Map<Object?, Object?> m) => TransferModeWriteReply(
        armed: hpiBool(m['armed']),
      );

  /// `armed`
  final bool? armed;
}

/// Request map for `wifi_status` (0x0070), read op.
Map<String, Object?> wifiStatusRequest() => const {};

/// Reply to `wifi_status` (0x0070), read op.
class WifiStatusReply {
  const WifiStatusReply({this.state, this.rssi, this.ssid, this.ip});

  factory WifiStatusReply.fromMap(Map<Object?, Object?> m) => WifiStatusReply(
        state: hpiInt(m['state']),
        rssi: hpiInt(m['rssi']),
        ssid: hpiStr(m['ssid']),
        ip: hpiStr(m['ip']),
      );

  /// `state`
  final int? state;

  /// `rssi`
  final int? rssi;

  /// `ssid`
  final String? ssid;

  /// `ip`
  final String? ip;
}

/// Request map for `wifi_scan` (0x0071), read op.
Map<String, Object?> wifiScanRequest() => const {};

/// Request map for `wifi_set` (0x0072), write op.
Map<String, Object?> wifiSetRequest({required String ssid, required String pw}) => {
      'ssid': ssid,
      'pw': pw,
    };

/// Reply to `wifi_set` (0x0072), write op.
class WifiSetReply {
  const WifiSetReply({this.ok});

  factory WifiSetReply.fromMap(Map<Object?, Object?> m) => WifiSetReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `wifi_forget` (0x0073), write op.
Map<String, Object?> wifiForgetRequest() => const {};

/// Reply to `wifi_forget` (0x0073), write op.
class WifiForgetReply {
  const WifiForgetReply({this.ok});

  factory WifiForgetReply.fromMap(Map<Object?, Object?> m) => WifiForgetReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `wifi_softap` (0x0074), write op.
Map<String, Object?> wifiSoftapRequest() => const {};

/// Reply to `wifi_softap` (0x0074), write op.
class WifiSoftapReply {
  const WifiSoftapReply({this.ok});

  factory WifiSoftapReply.fromMap(Map<Object?, Object?> m) => WifiSoftapReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `conn_enable` (0x0075), write op.
Map<String, Object?> connEnableRequest({required int radios}) => {
      'radios': radios,
    };

/// Reply to `conn_enable` (0x0075), write op.
class ConnEnableReply {
  const ConnEnableReply({this.ok});

  factory ConnEnableReply.fromMap(Map<Object?, Object?> m) => ConnEnableReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `conn_disable` (0x0076), write op.
Map<String, Object?> connDisableRequest() => const {};

/// Reply to `conn_disable` (0x0076), write op.
class ConnDisableReply {
  const ConnDisableReply({this.ok});

  factory ConnDisableReply.fromMap(Map<Object?, Object?> m) => ConnDisableReply(
        ok: hpiBool(m['ok']),
      );

  /// `ok`
  final bool? ok;
}

/// Request map for `conn_status` (0x0077), read op.
Map<String, Object?> connStatusRequest() => const {};

/// Reply to `conn_status` (0x0077), read op.
class ConnStatusReply {
  const ConnStatusReply({this.link, this.radios, this.state, this.rssi, this.ssid, this.ip, this.bleAdv, this.bleConn});

  factory ConnStatusReply.fromMap(Map<Object?, Object?> m) => ConnStatusReply(
        link: hpiInt(m['link']),
        radios: hpiInt(m['radios']),
        state: hpiInt(m['state']),
        rssi: hpiInt(m['rssi']),
        ssid: hpiStr(m['ssid']),
        ip: hpiStr(m['ip']),
        bleAdv: hpiBool(m['ble_adv']),
        bleConn: hpiBool(m['ble_conn']),
      );

  /// `link`
  final int? link;

  /// `radios`
  final int? radios;

  /// `state`
  final int? state;

  /// `rssi`
  final int? rssi;

  /// `ssid`
  final String? ssid;

  /// `ip`
  final String? ip;

  /// `ble_adv`
  final bool? bleAdv;

  /// `ble_conn`
  final bool? bleConn;
}

/// Request map for `diag_run_selftest` (0x0080), read op.
Map<String, Object?> diagRunSelftestRequest() => const {};

/// Reply to `diag_run_selftest` (0x0080), read op.
class DiagRunSelftestReply {
  const DiagRunSelftestReply({this.suiteVer, this.sd, this.batt, this.ecg, this.ppg, this.m4, this.qspi, this.pass, this.fail, this.healthOverall, this.health});

  factory DiagRunSelftestReply.fromMap(Map<Object?, Object?> m) => DiagRunSelftestReply(
        suiteVer: hpiInt(m['suite_ver']),
        sd: hpiBool(m['sd']),
        batt: hpiBool(m['batt']),
        ecg: hpiBool(m['ecg']),
        ppg: hpiBool(m['ppg']),
        m4: hpiBool(m['m4']),
        qspi: hpiBool(m['qspi']),
        pass: hpiInt(m['pass']),
        fail: hpiInt(m['fail']),
        healthOverall: hpiInt(m['health_overall']),
        health: DiagRunSelftestReplyHealth.fromValue(m['health']),
      );

  /// `suite_ver`
  final int? suiteVer;

  /// `sd`
  final bool? sd;

  /// `batt`
  final bool? batt;

  /// `ecg`
  final bool? ecg;

  /// `ppg`
  final bool? ppg;

  /// `m4`
  final bool? m4;

  /// `qspi`
  final bool? qspi;

  /// `pass`
  final int? pass;

  /// `fail`
  final int? fail;

  /// `health_overall`
  final int? healthOverall;

  /// `health` — per-subsystem state
  final DiagRunSelftestReplyHealth? health;
}

/// The `health` map of [DiagRunSelftestReply].
class DiagRunSelftestReplyHealth {
  const DiagRunSelftestReplyHealth({this.acq, this.m4, this.stream, this.rec, this.hl});

  factory DiagRunSelftestReplyHealth.fromMap(Map<Object?, Object?> m) => DiagRunSelftestReplyHealth(
        acq: hpiInt(m['acq']),
        m4: hpiInt(m['m4']),
        stream: hpiInt(m['stream']),
        rec: hpiInt(m['rec']),
        hl: hpiInt(m['hl']),
      );

  static DiagRunSelftestReplyHealth? fromValue(Object? v) =>
      v is Map ? DiagRunSelftestReplyHealth.fromMap(v) : null;

  /// `acq`
  final int? acq;

  /// `m4`
  final int? m4;

  /// `stream`
  final int? stream;

  /// `rec`
  final int? rec;

  /// `hl`
  final int? hl;
}

/// Request map for `diag_lead_off` (0x0081), read op.
Map<String, Object?> diagLeadOffRequest() => const {};

/// Reply to `diag_lead_off` (0x0081), read op.
class DiagLeadOffReply {
  const DiagLeadOffReply({this.mask, this.ra, this.la, this.ll, this.v1, this.ageMs, this.ok, this.hr, this.hrSrc, this.vflags});

  factory DiagLeadOffReply.fromMap(Map<Object?, Object?> m) => DiagLeadOffReply(
        mask: hpiInt(m['mask']),
        ra: hpiBool(m['ra']),
        la: hpiBool(m['la']),
        ll: hpiBool(m['ll']),
        v1: hpiBool(m['v1']),
        ageMs: hpiInt(m['age_ms']),
        ok: hpiBool(m['ok']),
        hr: hpiInt(m['hr']),
        hrSrc: hpiInt(m['hr_src']),
        vflags: hpiInt(m['vflags']),
      );

  /// `mask` — electrode bits: 1 RA, 2 LA, 4 LL, 8 V1
  final int? mask;

  /// `ra` — RA electrode is off
  final bool? ra;

  /// `la`
  final bool? la;

  /// `ll`
  final bool? ll;

  /// `v1`
  final bool? v1;

  /// `age_ms` — since acquisition last updated the mask
  final int? ageMs;

  /// `ok` — the state is fresh (the ECG front end is live)
  final bool? ok;

  /// `hr` — last heart rate, 0 = none
  final int? hr;

  /// `hr_src` — 0 = ECG, 1 = PPG
  final int? hrSrc;

  /// `vflags` — raw hp6_vitals.flags
  final int? vflags;
}

/// Request map for `m4fw_begin` (0x00A0), write op.
Map<String, Object?> m4fwBeginRequest({required int len, required List<int> sha, List<int>? sig}) => {
      'len': len,
      'sha': Uint8List.fromList(sha),
      if (sig != null) 'sig': Uint8List.fromList(sig),
    };

/// Request map for `m4fw_chunk` (0x00A1), write op.
Map<String, Object?> m4fwChunkRequest({required int off, required List<int> data}) => {
      'off': off,
      'data': Uint8List.fromList(data),
    };

/// Reply to `m4fw_chunk` (0x00A1), write op.
class M4fwChunkReply {
  const M4fwChunkReply({this.off});

  factory M4fwChunkReply.fromMap(Map<Object?, Object?> m) => M4fwChunkReply(
        off: hpiInt(m['off']),
      );

  /// `off` — next expected offset
  final int? off;
}

/// Request map for `m4fw_commit` (0x00A2), write op.
Map<String, Object?> m4fwCommitRequest() => const {};

/// Reply to `m4fw_commit` (0x00A2), write op.
class M4fwCommitReply {
  const M4fwCommitReply({this.rst});

  factory M4fwCommitReply.fromMap(Map<Object?, Object?> m) => M4fwCommitReply(
        rst: hpiBool(m['rst']),
      );

  /// `rst` — a reset is required
  final bool? rst;
}

/// Request map for `m4fw_status` (0x00A3), read op.
Map<String, Object?> m4fwStatusRequest() => const {};

/// Reply to `m4fw_status` (0x00A3), read op.
class M4fwStatusReply {
  const M4fwStatusReply({this.st, this.len, this.rx, this.err, this.rst, this.sig});

  factory M4fwStatusReply.fromMap(Map<Object?, Object?> m) => M4fwStatusReply(
        st: hpiInt(m['st']),
        len: hpiInt(m['len']),
        rx: hpiInt(m['rx']),
        err: hpiInt(m['err']),
        rst: hpiBool(m['rst']),
        sig: hpiBool(m['sig']),
      );

  /// `st` — state
  final int? st;

  /// `len` — total size
  final int? len;

  /// `rx` — bytes received
  final int? rx;

  /// `err`
  final int? err;

  /// `rst` — reset required
  final bool? rst;

  /// `sig` — this firmware requires a signature
  final bool? sig;
}

/// Request map for `m4fw_abort` (0x00A4), write op.
Map<String, Object?> m4fwAbortRequest() => const {};

/// Request map for `enter_recovery` (0x00A5), read op.
Map<String, Object?> enterRecoveryRequest() => const {};

/// Reply to `enter_recovery` (0x00A5), read op.
class EnterRecoveryReply {
  const EnterRecoveryReply({this.av, this.armed});

  factory EnterRecoveryReply.fromMap(Map<Object?, Object?> m) => EnterRecoveryReply(
        av: hpiBool(m['av']),
        armed: hpiBool(m['armed']),
      );

  /// `av` — available
  final bool? av;

  /// `armed`
  final bool? armed;
}

/// Request map for `enter_recovery` (0x00A5), write op.
Map<String, Object?> enterRecoveryWriteRequest({required bool arm, required bool rst}) => {
      'arm': arm,
      'rst': rst,
    };

/// Reply to `enter_recovery` (0x00A5), write op.
class EnterRecoveryWriteReply {
  const EnterRecoveryWriteReply({this.armed, this.rst});

  factory EnterRecoveryWriteReply.fromMap(Map<Object?, Object?> m) => EnterRecoveryWriteReply(
        armed: hpiBool(m['armed']),
        rst: hpiBool(m['rst']),
      );

  /// `armed`
  final bool? armed;

  /// `rst` — will reset
  final bool? rst;
}

/// Group-64 error codes (SMP v2 `err.rc` with `err.group == 64`).
const Map<int, HpiErrorCode> hpiErrors = {
  256: HpiErrorCode(256, 'NOT_READY', 'busy, or a prerequisite is missing (no card, dev build)'),
  257: HpiErrorCode(257, 'HW_FAULT', 'hardware or co-processor link failure'),
  258: HpiErrorCode(258, 'CHANNEL_NOT_AVAILABLE', 'this device cannot produce that stream channel'),
  259: HpiErrorCode(259, 'INSUFFICIENT_STORAGE', 'not enough space'),
  260: HpiErrorCode(260, 'TRANSFER_INVALID', 'transfer state is invalid'),
  261: HpiErrorCode(261, 'VERSION_MISMATCH', 'version mismatch'),
  262: HpiErrorCode(262, 'CONFIG_KEY_UNKNOWN', 'unknown settings key'),
  263: HpiErrorCode(263, 'CONFIG_TYPE_MISMATCH', 'settings value has the wrong type'),
  264: HpiErrorCode(264, 'LOCK_CHALLENGE_MISSING', 'unlock_response without a prior challenge'),
  265: HpiErrorCode(265, 'LOCK_HMAC_INVALID', 'wrong unlock secret'),
  266: HpiErrorCode(266, 'LOCK_EXPIRED', 'challenge or grant TTL elapsed'),
  267: HpiErrorCode(267, 'NO_MEDIA', 'no SD card present'),
  268: HpiErrorCode(268, 'IMAGE_INVALID', 'digest or signature mismatch'),
  269: HpiErrorCode(269, 'IMAGE_TOO_LARGE', 'exceeds staging or bank 2'),
  270: HpiErrorCode(270, 'BUSY', 'an update is already in flight'),
  271: HpiErrorCode(271, 'IMAGE_NOT_M4', 'verifies, but is not an M4 image'),
};

/// Stock MCUmgr group error codes the device returns, by group id.
const Map<int, Map<int, String>> hpiStockErrors = {
  0: {
    0: 'OK',
    1: 'UNKNOWN',
    2: 'INVALID_FORMAT',
    3: 'QUERY_YIELDS_NO_ANSWER',
    4: 'RTC_NOT_SET',
    5: 'RTC_COMMAND_FAILED',
    6: 'QUERY_RESPONSE_VALUE_NOT_VALID',
    7: 'HEAP_STATS_FETCH_FAILED',
  },
};
