// Generates the HealthyPi 6 protocol definitions from the firmware's catalog.
//
//   dart run tool/gen_protocol.dart
//
// Inputs are snapshots committed under protocol/, produced by the firmware
// repo's host tool (healthypi-6-fw/tools/healthypi):
//
//   healthypi catalog --json --full > protocol/hpi_group64.json
//   healthypi catalog --formats     > protocol/hp6_formats.json
//
// Outputs (committed; CI regenerates and fails on any diff):
//
//   lib/protocol/hpi_group64.g.dart  group-64 commands, request builders,
//                                    typed replies, error table
//   lib/protocol/hp6_formats.g.dart  DBLK channel ids, payload sizes, flags
//
// The firmware's own CI checks catalog.py against the C sources, so a Studio
// snapshot taken from it is as current as the firmware it came from.

import 'dart:convert';
import 'dart:io';

const _header = '// GENERATED by tool/gen_protocol.dart — do not edit.\n';

void main(List<String> args) {
  final root = File.fromUri(Platform.script).parent.parent.path;
  String path(String p) => '$root/$p';

  final catalog = jsonDecode(File(path('protocol/hpi_group64.json')).readAsStringSync())
      as Map<String, dynamic>;
  final formats = jsonDecode(File(path('protocol/hp6_formats.json')).readAsStringSync())
      as Map<String, dynamic>;

  File(path('lib/protocol/hpi_group64.g.dart')).writeAsStringSync(_group64(catalog));
  File(path('lib/protocol/hp6_formats.g.dart')).writeAsStringSync(_formats(formats));
  stdout.writeln('✅ generated lib/protocol/hpi_group64.g.dart, hp6_formats.g.dart');
}

// --------------------------------------------------------------- naming ----

const _reserved = {
  'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch',
  'class', 'const', 'continue', 'default', 'do', 'dynamic', 'else', 'enum',
  'extends', 'false', 'final', 'finally', 'for', 'if', 'in', 'is', 'new',
  'null', 'return', 'super', 'switch', 'this', 'throw', 'true', 'try', 'var',
  'void', 'while', 'with', 'hashCode', 'runtimeType', 'toString',
};

String _camel(String snake) {
  final parts = snake.toLowerCase().split('_').where((p) => p.isNotEmpty).toList();
  final s = parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  return _reserved.contains(s) ? '${s}_' : s;
}

String _pascal(String snake) {
  final c = _camel(snake).replaceAll(RegExp(r'_$'), '');
  return c[0].toUpperCase() + c.substring(1);
}

String _str(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

String _doc(String text, String indent) => text.isEmpty
    ? ''
    : text
        .split('\n')
        .map((l) => '$indent///${l.isEmpty ? '' : ' $l'}\n')
        .join();

// ------------------------------------------------------------- group 64 ----

String _dartType(Map<String, dynamic> f, String nestedClass) => switch (f['type']) {
      'uint' || 'int' => 'int',
      'bool' => 'bool',
      'tstr' => 'String',
      'bstr' => 'Uint8List',
      'map' => (f['nested'] as List?)?.isNotEmpty == true
          ? nestedClass
          : 'Map<Object?, Object?>',
      final t => throw FormatException('unknown field type $t'),
    };

String _reader(Map<String, dynamic> f, String nestedClass, String expr) =>
    switch (f['type']) {
      'uint' || 'int' => 'hpiInt($expr)',
      'bool' => 'hpiBool($expr)',
      'tstr' => 'hpiStr($expr)',
      'bstr' => 'hpiBytes($expr)',
      'map' => (f['nested'] as List?)?.isNotEmpty == true
          ? '$nestedClass.fromValue($expr)'
          : 'hpiMap($expr)',
      final t => throw FormatException('unknown field type $t'),
    };

/// A reply class (and any nested map classes) for [fields].
void _replyClass(StringBuffer out, String name, String doc,
    List<Map<String, dynamic>> fields) {
  final nested = <(String, List<Map<String, dynamic>>, String)>[];
  out.write(_doc(doc, ''));
  out.writeln('class $name {');
  out.writeln('  const $name({${fields.map((f) => 'this.${_camel(f['name'])}').join(', ')}});');
  out.writeln();
  out.writeln('  factory $name.fromMap(Map<Object?, Object?> m) => $name(');
  for (final f in fields) {
    final nc = '$name${_pascal(f['name'])}';
    out.writeln('        ${_camel(f['name'])}: ${_reader(f, nc, "m[${_str(f['name'])}]")},');
  }
  out.writeln('      );');
  if (name.contains(RegExp(r'Reply.+'))) {
    // nested map type: parse from an untyped value
    out.writeln();
    out.writeln('  static $name? fromValue(Object? v) =>');
    out.writeln('      v is Map ? $name.fromMap(v) : null;');
  }
  for (final f in fields) {
    final nc = '$name${_pascal(f['name'])}';
    out.writeln();
    out.write(_doc(
        [
          '`${f['name']}`${f['optional'] == true ? ' (optional)' : ''}',
          if ((f['doc'] as String?)?.isNotEmpty == true) f['doc'] as String,
        ].join(' — '),
        '  '));
    out.writeln('  final ${_dartType(f, nc)}? ${_camel(f['name'])};');
    final n = (f['nested'] as List?)?.cast<Map<String, dynamic>>();
    if (f['type'] == 'map' && n != null && n.isNotEmpty) {
      nested.add((nc, n, 'The `${f['name']}` map of [$name].'));
    }
  }
  out.writeln('}');
  for (final (nc, n, d) in nested) {
    out.writeln();
    _replyClass(out, nc, d, n);
  }
}

/// A request-map builder for [fields].
void _requestBuilder(StringBuffer out, String fn, String doc,
    List<Map<String, dynamic>> fields) {
  out.write(_doc(doc, ''));
  if (fields.isEmpty) {
    out.writeln('Map<String, Object?> $fn() => const {};');
    return;
  }
  final params = fields.map((f) {
    final t = switch (f['type']) {
      'uint' || 'int' => 'int',
      'bool' => 'bool',
      'tstr' => 'String',
      'bstr' => 'List<int>',
      _ => 'Map<String, Object?>',
    };
    return f['optional'] == true
        ? '$t? ${_camel(f['name'])}'
        : 'required $t ${_camel(f['name'])}';
  }).join(', ');
  out.writeln('Map<String, Object?> $fn({$params}) => {');
  for (final f in fields) {
    final v = _camel(f['name']);
    final value = f['type'] == 'bstr' ? 'Uint8List.fromList($v)' : v;
    final key = _str(f['name']);
    out.writeln(switch ((f['optional'] == true, f['type'] == 'bstr')) {
      (true, true) => '      if ($v != null) $key: $value,',
      (true, false) => '      $key: ?$v,',
      _ => '      $key: $value,',
    });
  }
  out.writeln('    };');
}

String _group64(Map<String, dynamic> c) {
  final out = StringBuffer(_header)
    ..writeln('// Source: protocol/hpi_group64.json '
        '(healthypi ${c['tool_version']}, schema 0x${(c['schema_version'] as int).toRadixString(16).padLeft(4, '0')}).')
    ..writeln('// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import 'hpi_command.dart';")
    ..writeln()
    ..writeln('/// Group-64 schema version this file was generated from.')
    ..writeln('const int hpiSchemaVersion = ${c['schema_version']};')
    ..writeln();

  final commands = (c['commands'] as List).cast<Map<String, dynamic>>();

  out.writeln('/// Every group-64 command id the firmware declares.');
  out.writeln('abstract final class Hpi {');
  for (final cmd in commands) {
    final ops = (cmd['ops'] as List).cast<String>();
    final errors = (cmd['errors'] as List?)?.cast<int>() ?? const <int>[];
    final args = [
      _str(cmd['name']),
      if (ops.contains('read')) 'read: true',
      if (ops.contains('write')) 'write: true',
      if (cmd['status'] != 'live') 'status: HpiStatus.${cmd['status']}',
      if (cmd['unlock'] == true) 'unlock: true',
      if (cmd['signed_build'] == true) 'signedBuild: true',
      if (errors.isNotEmpty) 'errors: [${errors.join(', ')}]',
    ];
    out.write(_doc((cmd['doc'] as String?) ?? '', '  '));
    out.writeln('  static const ${_camel(cmd['name'])} = HpiCommand(${cmd['id']}, ${args.join(', ')});');
  }
  out.writeln();
  out.writeln('  static const List<HpiCommand> all = [');
  for (final cmd in commands) {
    out.writeln('    ${_camel(cmd['name'])},');
  }
  out.writeln('  ];');
  out.writeln('}');

  for (final cmd in commands) {
    final ops = (cmd['ops'] as List).cast<String>();
    if (ops.isEmpty) continue;
    final name = cmd['name'] as String;
    List<Map<String, dynamic>>? fields(String k) =>
        (cmd[k] as List?)?.cast<Map<String, dynamic>>();
    final hasWriteSchema =
        cmd.containsKey('write_request') || cmd.containsKey('write_response');
    final label = '`$name` (${cmd['id']})';

    // The primary schema: read if the command reads, else write.
    final primaryOp = ops.contains('read') ? 'read' : 'write';
    out.writeln();
    _requestBuilder(out, '${_camel(name)}Request',
        'Request map for $label, $primaryOp op.', fields('request') ?? const []);
    final rsp = fields('response');
    if (rsp != null) {
      out.writeln();
      _replyClass(out, '${_pascal(name)}Reply', 'Reply to $label, $primaryOp op.', rsp);
    }
    if (hasWriteSchema) {
      out.writeln();
      _requestBuilder(out, '${_camel(name)}WriteRequest',
          'Request map for $label, write op.', fields('write_request') ?? const []);
      final wrsp = fields('write_response');
      if (wrsp != null) {
        out.writeln();
        _replyClass(out, '${_pascal(name)}WriteReply', 'Reply to $label, write op.', wrsp);
      }
    }
  }

  final errors = (c['errors'] as Map).cast<String, String>();
  final hints = (c['error_hints'] as Map? ?? const {}).cast<String, String>();
  out.writeln();
  out.writeln('/// Group-64 error codes (SMP v2 `err.rc` with `err.group == 64`).');
  out.writeln('const Map<int, HpiErrorCode> hpiErrors = {');
  for (final e in errors.entries) {
    out.writeln('  ${e.key}: HpiErrorCode(${e.key}, ${_str(e.value)}, ${_str(hints[e.key] ?? '')}),');
  }
  out.writeln('};');

  final stock = (c['stock_errors'] as Map? ?? const {}).cast<String, Map>();
  out.writeln();
  out.writeln('/// Stock MCUmgr group error codes the device returns, by group id.');
  out.writeln('const Map<int, Map<int, String>> hpiStockErrors = {');
  for (final g in stock.entries) {
    out.writeln('  ${g.key}: {');
    for (final e in g.value.cast<String, String>().entries) {
      out.writeln('    ${e.key}: ${_str(e.value)},');
    }
    out.writeln('  },');
  }
  out.writeln('};');
  return out.toString();
}

// -------------------------------------------------------------- formats ----

String _formats(Map<String, dynamic> f) {
  final channels = (f['channels'] as Map).cast<String, int>();
  final payloads = (f['payloads'] as Map).cast<String, Map>();
  final flags = (f['flags'] as Map).cast<String, Map>();
  final out = StringBuffer(_header)
    ..writeln('// Source: protocol/hp6_formats.json (healthypi ${f['tool_version']}),')
    ..writeln('// the host mirror of app_m7/src/core/sample_formats.h.')
    ..writeln()
    ..writeln('/// `.HP6` format version these layouts describe.')
    ..writeln('const int hp6FormatVersion = ${f['file_version']};')
    ..writeln()
    ..writeln('/// DBLK frame: header, payload, trailing CRC-32.')
    ..writeln('const int dblkHeaderLen = ${f['dblk_header_len']};')
    ..writeln('const int dblkCrcLen = ${f['dblk_crc_len']};')
    ..writeln('const int dblkOverhead = dblkHeaderLen + dblkCrcLen;')
    ..writeln()
    ..writeln('/// DBLK channel ids (header byte 20).')
    ..writeln('abstract final class Hp6Channel {');
  for (final e in channels.entries) {
    out.writeln('  static const int ${_camel(e.key)} = ${e.value};');
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('/// Bytes per sample struct, by channel. A block whose payload does not')
    ..writeln('/// divide into these is a layout mismatch and is rejected.')
    ..writeln('const Map<int, int> hp6SampleSize = {');
  for (final e in payloads.entries) {
    out.writeln('  Hp6Channel.${_camel(e.key)}: ${e.value['size']}, // ${e.value['struct']}');
  }
  out.writeln('};');

  const classes = {
    'lead_off': ('Hp6LeadOff', '`hp6_ecg_sample.lead_off`: electrode bits, set = off.'),
    'vitals': ('Hp6VitalsFlag', '`hp6_vitals.flags`: HR provenance and quality.'),
    'infer': ('Hp6InferFlag', '`hp6_infer_sample.flags`.'),
  };
  for (final e in flags.entries) {
    final (cls, doc) = classes[e.key] ?? ('Hp6${_pascal(e.key)}Flag', '');
    out
      ..writeln()
      ..write(_doc(doc, ''))
      ..writeln('abstract final class $cls {');
    for (final b in e.value.cast<String, int>().entries) {
      out.writeln('  static const int ${_camel(b.key)} = 0x${b.value.toRadixString(16).padLeft(2, '0')};');
    }
    out.writeln('}');
  }
  return out.toString();
}
